name       : haskell-hxt-unicode
version    : 9.0.2.4
release    : 3
source     :
    - https://hackage.haskell.org/package/hxt-unicode-9.0.2.4/hxt-unicode-9.0.2.4.tar.gz : 7b5823f3bd94b57022d9d84ab3555303653c5121eaaef2ee1fd4918f3c434466
license    : MIT
component  : programming.haskell
summary    : Unicode encoding and decoding functions for utf8, iso-latin-* and somes other encodings, used in the Haskell XML Toolbox
description: |
    Unicode encoding and decoding functions for utf8, iso-latin-* and somes other encodings, used in the Haskell XML Toolbox
builddeps  :
    - haskell-cabal-install
    - haskell-hxt-charproperties-devel
rundeps    :
    - devel:
        - haskell-hxt-charproperties-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
